# Simple Makefile
# @author Jatin Chowdhary

# INSTRUCTIONS #
# Change 'filename' to the name of the C source file, without the
# extension. For example, if the C source file is 'program.c',
# then `FILE=program`.
FILE=filename

all:
	gcc $(FILE).c -o $(FILE)

clean:
	rm -rf $(FILE)

# INFORMATION #
# Type "make", without the quotes to compile a simple C program
# Type "make clean", without the quotes to delete the compiled C
#   program created by `gcc`.
#   Note: This (simple) Makefile does not create Object file(s)
