all: lab5_1 lab5_2

lab5_2: lab5_2.o asm_io.o driver.c
         gcc -m32 -o lab5_2 lab5_2.o driver.c asm_io.o
lab5_1: lab5_1.o asm_io.o driver.c
         gcc -m32 -o lab5_1 lab5_1.o driver.c asm_io.o
asm_io.o: asm_io.asm
        nasm -f elf32 -d ELF_TYPE asm_io.asm
lab5_2.o: lab5_2.asm
        nasm -f elf32 -o lab5_2.o lab5_2.asm
lab5_1.o: lab5_1.asm
        nasm -f elf32 -o lab5_1.o lab5_1.asm
clean:
        rm *.o lab5_1 lab5_2
